version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/receipt-data-extraction/
permissions:
  - object: /home/ubuntu/receipt-data-extraction/
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 1200
      runas: root
