version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/receipt-data-extraction/
    file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/cloud-tech-webapp/
    pattern: "**"
    owner: root
    group: root
